const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    //admin
    FETCH_GENDER_START: "FETCH_GENDER_START",
    FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
    FETCH_GENDER_FAIDED: "FETCH_GENDER_FAILED",

    FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
    FETCH_ROLE_FAIDED: "FETCH_ROLE_FAILED",

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    EDIT_USER_FAILED: 'EDIT_USER_FAILED',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
    FETCH_ALL_USERS_FAILED: "FETCH_ALL_USERS_FAILED",

    GET_ALL_ROLE_SUCCESS: "GET_ALL_ROLE_SUCCESS",
    GET_ALL_ROLE_FAILED: "GET_ALL_ROLE_FAILED",


    CREATE_LOCATION_SUCCESS: 'CREATE_LOCATION_SUCCESS',
    CREATE_LOCATION_FAILED: 'CREATE_LOCATION_FAILED',

    EDIT_LOCATION_FAILED: 'EDIT_LOCATION_FAILED',
    EDIT_LOCATION_SUCCESS: 'EDIT_LOCATION_SUCCESS',

    DELETE_LOCATION_SUCCESS: 'DELETE_LOCATION_SUCCESS',
    DELETE_LOCATION_FAILED: 'DELETE_LOCATION_FAILED',

    FETCH_ALL_LOCATIONS_SUCCESS: "FETCH_ALL_LOCATIONS_SUCCESS",
    FETCH_ALL_LOCATIONS_FAILED: "FETCH_ALL_LOCATIONS_FAILED",

    FETCH_ALL_LOCATION_BY_USERID_SUCCESS: "FETCH_ALL_LOCATION_BY_USERID_SUCCESS",
    FETCH_ALL_LOCATION_BY_USERID_FAILED: "FETCH_ALL_LOCATION_BY_USERID_FAILED",


    CREATE_CHARGER_SUCCESS: 'CREATE_CHARGER_SUCCESS',
    CREATE_CHARGER_FAILED: 'CREATE_CHARGER_FAILED',

    EDIT_CHARGER_FAILED: 'EDIT_CHARGER_FAILED',
    EDIT_CHARGER_SUCCESS: 'EDIT_CHARGER_SUCCESS',

    DELETE_CHARGER_SUCCESS: 'DELETE_CHARGER_SUCCESS',
    DELETE_CHARGER_FAILED: 'DELETE_CHARGER_FAILED',

    FETCH_ALL_CHARGERS_SUCCESS: "FETCH_ALL_CHARGERS_SUCCESS",
    FETCH_ALL_CHARGERS_FAILED: "FETCH_ALL_CHARGERS_FAILED",

    FETCH_ALL_CHARGER_BY_LOCATIONID_SUCCESS: "FETCH_ALL_CHARGER_BY_LOCATIONID_SUCCESS",
    FETCH_ALL_CHARGER_BY_LOCATIONID_FAILED: "FETCH_ALL_CHARGER_BY_LOCATIONID_FAILED",


    CREATE_TYPE_SUCCESS: 'CREATE_TYPE_SUCCESS',
    CREATE_TYPE_FAILED: 'CREATE_TYPE_FAILED',

    EDIT_TYPE_FAILED: 'EDIT_TYPE_FAILED',
    EDIT_TYPE_SUCCESS: 'EDIT_TYPE_SUCCESS',

    DELETE_TYPE_SUCCESS: 'DELETE_TYPE_SUCCESS',
    DELETE_TYPE_FAILED: 'DELETE_TYPE_FAILED',

    FETCH_ALL_TYPES_SUCCESS: "FETCH_ALL_TYPES_SUCCESS",
    FETCH_ALL_TYPES_FAILED: "FETCH_ALL_TYPES_FAILED",

    FETCH_ALL_TYPE_BY_CHARGERID_SUCCESS: "FETCH_ALL_TYPE_BY_CHARGERID_SUCCESS",
    FETCH_ALL_TYPE_BY_CHARGERID_FAILED: "FETCH_ALL_TYPE_BY_CHARGERID_FAILED",



    CREATE_RESERVATION_SUCCESS: 'CREATE_RESERVATION_SUCCESS',
    CREATE_RESERVATION_FAILED: 'CREATE_RESERVATION_FAILED',

    EDIT_RESERVATION_FAILED: 'EDIT_RESERVATION_FAILED',
    EDIT_RESERVATION_SUCCESS: 'EDIT_RESERVATION_SUCCESS',

    DELETE_RESERVATION_SUCCESS: 'DELETE_RESERVATION_SUCCESS',
    DELETE_RESERVATION_FAILED: 'DELETE_RESERVATION_FAILED',

    FETCH_ALL_RESERVATIONS_SUCCESS: "FETCH_ALL_RESERVATIONS_SUCCESS",
    FETCH_ALL_RESERVATIONS_FAILED: "FETCH_ALL_RESERVATIONS_FAILED",


    CREATE_HISTORY_SUCCESS: 'CREATE_HISTORY_SUCCESS',
    CREATE_HISTORY_FAILED: 'CREATE_HISTORY_FAILED',

    EDIT_HISTORY_FAILED: 'EDIT_HISTORY_FAILED',
    EDIT_HISTORY_SUCCESS: 'EDIT_HISTORY_SUCCESS',

    DELETE_HISTORY_SUCCESS: 'DELETE_HISTORY_SUCCESS',
    DELETE_HISTORY_FAILED: 'DELETE_HISTORY_FAILED',

    FETCH_ALL_HISTORYS_SUCCESS: "FETCH_ALL_HISTORYS_SUCCESS",
    FETCH_ALL_HISTORYS_FAILED: "FETCH_ALL_HISTORYS_FAILED",


    CREATE_INFO_SUCCESS: 'CREATE_INFO_SUCCESS',
    CREATE_INFO_FAILED: 'CREATE_INFO_FAILED',

    EDIT_INFO_FAILED: 'EDIT_INFO_FAILED',
    EDIT_INFO_SUCCESS: 'EDIT_INFO_SUCCESS',

    DELETE_INFO_SUCCESS: 'DELETE_INFO_SUCCESS',
    DELETE_INFO_FAILED: 'DELETE_INFO_FAILED',

    FETCH_ALL_INFOS_SUCCESS: "FETCH_ALL_INFOS_SUCCESS",
    FETCH_ALL_INFOS_FAILED: "FETCH_ALL_INFOS_FAILED",
    

    CREATE_FEEDBACK_SUCCESS: 'CREATE_FEEDBACK_SUCCESS',
    CREATE_FEEDBACK_FAILED: 'CREATE_FEEDBACK_FAILED',

    EDIT_FEEDBACK_FAILED: 'EDIT_FEEDBACK_FAILED',
    EDIT_FEEDBACK_SUCCESS: 'EDIT_FEEDBACK_SUCCESS',

    DELETE_FEEDBACK_SUCCESS: 'DELETE_FEEDBACK_SUCCESS',
    DELETE_FEEDBACK_FAILED: 'DELETE_FEEDBACK_FAILED',

    FETCH_ALL_FEEDBACKS_SUCCESS: "FETCH_ALL_FEEDBACKS_SUCCESS",
    FETCH_ALL_FEEDBACKS_FAILED: "FETCH_ALL_FEEDBACKS_FAILED",

    
    CREATE_DEVICE_SUCCESS: 'CREATE_DEVICE_SUCCESS',
    CREATE_DEVICE_FAILED: 'CREATE_DEVICE_FAILED',

    EDIT_DEVICE_FAILED: 'EDIT_DEVICE_FAILED',
    EDIT_DEVICE_SUCCESS: 'EDIT_DEVICE_SUCCESS',

    DELETE_DEVICE_SUCCESS: 'DELETE_DEVICE_SUCCESS',
    DELETE_DEVICE_FAILED: 'DELETE_DEVICE_FAILED',

    FETCH_ALL_DEVICES_SUCCESS: "FETCH_ALL_DEVICES_SUCCESS",
    FETCH_ALL_DEVICES_FAILED: "FETCH_ALL_DEVICES_FAILED",


    CREATE_MAINTENANCE_SUCCESS: 'CREATE_MAINTENANCE_SUCCESS',
    CREATE_MAINTENANCE_FAILED: 'CREATE_MAINTENANCE_FAILED',

    EDIT_MAINTENANCE_FAILED: 'EDIT_MAINTENANCE_FAILED',
    EDIT_MAINTENANCE_SUCCESS: 'EDIT_MAINTENANCE_SUCCESS',

    DELETE_MAINTENANCE_SUCCESS: 'DELETE_MAINTENANCE_SUCCESS',
    DELETE_MAINTENANCE_FAILED: 'DELETE_MAINTENANCE_FAILED',

    FETCH_ALL_MAINTENANCES_SUCCESS: "FETCH_ALL_MAINTENANCES_SUCCESS",
    FETCH_ALL_MAINTENANCES_FAILED: "FETCH_ALL_MAINTENANCES_FAILED",


    CREATE_NOTIFICATION_SUCCESS: 'CREATE_NOTIFICATION_SUCCESS',
    CREATE_NOTIFICATION_FAILED: 'CREATE_NOTIFICATION_FAILED',

    EDIT_NOTIFICATION_FAILED: 'EDIT_NOTIFICATION_FAILED',
    EDIT_NOTIFICATION_SUCCESS: 'EDIT_NOTIFICATION_SUCCESS',

    DELETE_NOTIFICATION_SUCCESS: 'DELETE_NOTIFICATION_SUCCESS',
    DELETE_NOTIFICATION_FAILED: 'DELETE_NOTIFICATION_FAILED',

    FETCH_ALL_NOTIFICATIONS_SUCCESS: "FETCH_ALL_NOTIFICATIONS_SUCCESS",
    FETCH_ALL_NOTIFICATIONS_FAILED: "FETCH_ALL_NOTIFICATIONS_FAILED",


    CREATE_OTP_SUCCESS: 'CREATE_OTP_SUCCESS',
    CREATE_OTP_FAILED: 'CREATE_OTP_FAILED',

    EDIT_OTP_FAILED: 'EDIT_OTP_FAILED',
    EDIT_OTP_SUCCESS: 'EDIT_OTP_SUCCESS',

    DELETE_OTP_SUCCESS: 'DELETE_OTP_SUCCESS',
    DELETE_OTP_FAILED: 'DELETE_OTP_FAILED',

    FETCH_ALL_OTPS_SUCCESS: "FETCH_ALL_OTPS_SUCCESS",
    FETCH_ALL_OTPS_FAILED: "FETCH_ALL_OTPS_FAILED",

})

export default actionTypes;